import twilio from "twilio";

import { TwilioVoiceProvider } from "../src/voice/twilio";

/** Signature and parsing cases never place a call, so this is never invoked. */
const stubAudio = {
	publish: async () => ({
		url: "https://app.example/api/audio/stub.mp3",
		id: "00000000-0000-4000-8000-000000000000",
	}),
};

let pass = 0;
let fail = 0;

function check(label: string, actual: unknown, expected: unknown) {
	const ok = JSON.stringify(actual) === JSON.stringify(expected);
	if (ok) {
		pass++;
		console.log(`  ok   ${label}`);
	} else {
		fail++;
		console.log(
			`  FAIL ${label}\n         expected ${JSON.stringify(expected)}\n         actual   ${JSON.stringify(actual)}`,
		);
	}
}

console.log(
	"\nSignature verification (cross-checked against the official Twilio SDK):",
);
{
	const AUTH_TOKEN = "12345";
	const provider = new TwilioVoiceProvider({
		accountSid: "ACtest",
		authToken: AUTH_TOKEN,
		fromNumber: "+14158675310",
		appUrl: "https://mycompany.com",
		audio: stubAudio,
	});

	const url = "https://mycompany.com/myapp.php?foo=1&bar=2";
	const params = {
		CallSid: "CA1234567890ABCDE",
		Caller: "+14158675310",
		Digits: "1234",
		From: "+14158675310",
		To: "+18005551212",
	};
	const body = new URLSearchParams(params).toString();

	// The expectation is DERIVED from Twilio's own implementation rather than a
	// hardcoded constant, so this stays honest even if their algorithm moves.
	const signature = twilio.getExpectedTwilioSignature(AUTH_TOKEN, url, params);

	check(
		"accepts a signature generated by the official SDK",
		provider.verifyWebhook({
			rawBody: body,
			headers: { "x-twilio-signature": signature },
			url,
		}),
		true,
	);

	check(
		"tampered body rejected",
		provider.verifyWebhook({
			rawBody: body.replace("1234", "9999"),
			headers: { "x-twilio-signature": signature },
			url,
		}),
		false,
	);

	check(
		"wrong URL rejected",
		provider.verifyWebhook({
			rawBody: body,
			headers: { "x-twilio-signature": signature },
			url: "https://evil.example/myapp.php?foo=1&bar=2",
		}),
		false,
	);

	check(
		"wrong auth token rejected",
		new TwilioVoiceProvider({
			accountSid: "ACtest",
			authToken: "wrong-token",
			fromNumber: "+14158675310",
			appUrl: "https://mycompany.com",
			audio: stubAudio,
		}).verifyWebhook({
			rawBody: body,
			headers: { "x-twilio-signature": signature },
			url,
		}),
		false,
	);

	check(
		"missing signature rejected",
		provider.verifyWebhook({ rawBody: body, headers: {}, url }),
		false,
	);
}

console.log("\nWebhook parsing:");
{
	const provider = new TwilioVoiceProvider({
		accountSid: "ACtest",
		authToken: "token",
		fromNumber: "+14158675310",
		appUrl: "https://app.example",
		audio: stubAudio,
	});

	const parse = (params: Record<string, string>) =>
		provider.parseWebhook({
			rawBody: new URLSearchParams(params).toString(),
			headers: {},
			url: "https://app.example/api/webhooks/twilio",
		});

	check("missing CallSid ignored", parse({ CallStatus: "ringing" }), null);

	const ringing = parse({ CallSid: "CA1", CallStatus: "ringing" });
	check(
		"ringing -> STATUS/RINGING",
		[ringing?.kind, (ringing as { status: string })?.status],
		["STATUS", "RINGING"],
	);

	const inProgress = parse({ CallSid: "CA1", CallStatus: "in-progress" });
	check(
		"in-progress -> IN_PROGRESS",
		(inProgress as { status: string })?.status,
		"IN_PROGRESS",
	);

	const completed = parse({
		CallSid: "CA1",
		CallStatus: "completed",
		CallDuration: "42",
	});
	check("completed -> ENDED", completed?.kind, "ENDED");
	check(
		"duration captured",
		(completed as { durationSeconds: number })?.durationSeconds,
		42,
	);

	const busy = parse({ CallSid: "CA1", CallStatus: "busy" });
	check("busy -> BUSY", (busy as { status: string })?.status, "BUSY");

	const noAnswer = parse({ CallSid: "CA1", CallStatus: "no-answer" });
	check(
		"no-answer -> NO_ANSWER",
		(noAnswer as { status: string })?.status,
		"NO_ANSWER",
	);

	// Answering-machine detection must never be counted as a human conversation.
	const machine = parse({
		CallSid: "CA1",
		CallStatus: "completed",
		AnsweredBy: "machine_start",
		CallDuration: "8",
	});
	check(
		"machine answer -> VOICEMAIL",
		(machine as { status: string })?.status,
		"VOICEMAIL",
	);

	const human = parse({
		CallSid: "CA1",
		CallStatus: "completed",
		AnsweredBy: "human",
		CallDuration: "30",
	});
	check(
		"human answer stays COMPLETED",
		(human as { status: string })?.status,
		"COMPLETED",
	);

	const recording = parse({
		CallSid: "CA1",
		RecordingSid: "RE1",
		RecordingUrl: "https://api.twilio.com/rec/RE1",
		RecordingDuration: "30",
	});
	check("recording callback -> ENDED", recording?.kind, "ENDED");
	check(
		"recording url gets .mp3 suffix",
		(recording as { recordingUrl: string })?.recordingUrl,
		"https://api.twilio.com/rec/RE1.mp3",
	);
}

console.log(`\n${pass} passed, ${fail} failed\n`);
process.exit(fail === 0 ? 0 : 1);
